{% set version = "0.6-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-corbi
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Corbi_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Corbi/Corbi_{{ version }}.tar.gz
  sha256: 4c84a94eb11bda0bf67115c6aa4f06271cfdaf101a8efaa4873c6fdae224539e

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-crf
    - r-matrix
    - r-mpmi
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-crf
    - r-matrix
    - r-mpmi

test:
  commands:
    - $R -e "library('Corbi')"           # [not win]
    - "\"%R%\" -e \"library('Corbi')\""  # [win]

about:
  home: https://github.com/wulingyun/Corbi
  license: GPL (>= 2)
  summary: Provides a bundle of basic and fundamental bioinformatics tools, such as network querying and alignment, subnetwork extraction and search, network biomarker identification.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr
