travis:
  secure:
    BINSTAR_TOKEN: PCvL3/2qiTg8/h1N/F0LmDFUDFHJxip4hsUTgFOClOxaoIbFMyOe/sQ2IjcN0AHGKNCX+/yn22Kvx6mDc3df1YYOMgactJZ8E0VgswIbT0CqwLNJdLORk2Dm7+Y+3QWfEGo7rUqHla50kx3VaVsPjfTAd5Zwuw1+d8cqLjPEZbx2Dtfpv932KVCCDWHOnZ2wNl75gYNinfxnOUCBRe5P6IuTv+767fWiRnb8SbIkTcZ3vTj8wEyMh3Wj58falVVwSowB5VXMyMhscqhucT4wMVDPPKQJOixxPTwVSjJ9zlhMJboCJ7F7AyLpqVKV0IqcMAGCj1tBGzgf5H++0z9CDZwE9yBDvaTXR3KFdXa8s5uoYYsi1+2rQM8eCFHkQm4sWZqaGgin2qHgu9GK+pn5d6VoiPXz/tv9DMVaMDnUnyRU5/pzNNuSqq8OLdgTWAy5ULcV8GJ0Z1BdrMUD96I5p7aFf/j1q5GSYCDE10AA0JvhZRt7S+4AET39k/q4VBxneNu1LHNW+59epcCZMfEfahvkG0e+inQBc+GQ9GRa6uoRUn3obGyLjsq8eUR5U9cxFfyAY/EK0Q74jZ5DAx05pJ0LuEgUAjA8pdZH+jYujju64UM4NFkeDmk2ouCcYVzFqjDdMmrW3EbSq4ItjTV5iidWdbBckQNqHPNL7f+9ZJg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
